version: 0.2
phases:
  pre_build:
    commands:
      - REGISTRY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REGISTRY_URI}
      - COMMIT_HASH=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | cut -c1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - REPOSITORY_URI=${REGISTRY_URI}/${IMAGE_REPO_NAME}
      - docker image build -t ${REPOSITORY_URI}:latest .
      - docker image tag ${REPOSITORY_URI}:latest ${REPOSITORY_URI}:${IMAGE_TAG}
  post_build:
    commands:
      - docker image push ${REPOSITORY_URI}:latest
      - docker image push ${REPOSITORY_URI}:${IMAGE_TAG}
      - |
        cat <<EOF > ${IMAGE_DEFINITIONS_FILE}
        [
          {
            "name": "${CONTAINER_NAME}",
            "imageUri": "${REPOSITORY_URI}:${IMAGE_TAG}"
          }
        ]
        EOF

artifacts:
  files: ${IMAGE_DEFINITIONS_FILE}
